### ISSUE TITLE
can you make this have all the stuff that minecraft wii u mod injector bullwiiplaza made but with extra mods including anti skin crash

### ISSUE THREAD

**Issue by Cxsmo-ai** [NexxtFax/EZ-CheatzV2#1]
can you make this have all the stuff that minecraft wii u mod injector bullwiiplaza made but with extra mods including anti skin crash

**Comment by NexxtFax** [comment]
I could do it but I have no motivation working on this right now. You can add it yourself if you want as the tool is open source.

**Comment by Cxsmo-ai** [comment]
do you know what the anti skin crash code is

**Comment by NexxtFax** [comment]
nah and I don't really care what it is because i'm not planning on countinuing development.
